name: crypto_display
description: A new Flutter application.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  charts_flutter: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
